# Generated by Django 5.0.4 on 2024-04-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department',
            new_name='course',
        ),
    ]
