# Generated by Django 5.0.4 on 2024-04-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_alter_department_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joining_date',
        ),
    ]
