# Generated by Django 5.0.4 on 2024-04-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_remove_user_date_of_birth_remove_user_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('principal', 'Principal'), ('teacher', 'Teacher'), ('student', 'Student')], default='principal', max_length=100),
        ),
    ]
