# Generated by Django 5.0.4 on 2024-04-09 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0011_remove_teachersdetails_teacher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersdetails',
            name='teacher_email',
            field=models.CharField(default=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teachersdetails',
            name='subject_taught',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='insta.subjectdetails'),
        ),
        migrations.AlterModelTable(
            name='teachersdetails',
            table='teacher_details',
        ),
    ]
