# Generated by Django 5.0.4 on 2024-04-09 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0012_teachersdetails_teacher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
