# Generated by Django 5.0.4 on 2024-04-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0013_user_date_of_birth_user_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joining_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='TeachersDetails',
        ),
    ]
