# Generated by Django 5.0.4 on 2024-04-09 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0014_alter_user_joining_date_delete_teachersdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetails',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profiledetails',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='ProfileDetails',
        ),
    ]
