# Generated by Django 5.0.4 on 2024-04-10 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0015_remove_profiledetails_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdetails',
            name='student',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.CharField(choices=[('EC', 'EC'), ('IT', 'IT'), ('COMPUTER', 'COMPUTER')], default='EC', max_length=100),
        ),
    ]
