# Generated by Django 5.0.4 on 2024-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0017_remove_subjectdetails_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10, null=True),
        ),
    ]
