# Generated by Django 5.0.4 on 2024-04-15 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0019_alter_user_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectdetails',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
